# Generated by Django 5.1 on 2024-08-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Mobile', models.BigIntegerField(null=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Role', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
