# Generated by Django 5.1 on 2024-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record_maintain', '0008_alter_employee_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='file',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
