# Generated by Django 5.1 on 2024-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record_maintain', '0012_historicalemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='file',
            field=models.TextField(max_length=100),
        ),
    ]
