# Generated by Django 5.1 on 2024-10-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record_maintain', '0013_alter_employee_file_alter_historicalemployee_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='file',
            field=models.FileField(max_length=500, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='file',
            field=models.TextField(max_length=500),
        ),
    ]
