# Generated by Django 5.1 on 2024-10-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record_maintain', '0015_alter_employee_file_alter_historicalemployee_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='file',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='file',
        ),
        migrations.CreateModel(
            name='employeefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Record_maintain.employee')),
            ],
        ),
    ]
