# Generated by Django 5.1 on 2024-10-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Record_maintain', '0016_remove_employee_file_remove_historicalemployee_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Empid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='employeefile',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Historicalemployee',
        ),
    ]
