# Generated by Django 5.1 on 2024-10-04 04:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record_maintain', '0017_remove_employee_email_remove_employee_empid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Empid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Mobile',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Role',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeefile',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Record_maintain.employee'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Historicalemployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Empid', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Mobile', models.BigIntegerField(null=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Role', models.CharField(max_length=30, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
