# Generated by Django 5.1 on 2024-10-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Record_maintain', '0020_employeefile_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefile',
            name='employee',
        ),
    ]
