# Generated by Django 5.1 on 2024-10-04 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record_maintain', '0021_remove_employeefile_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Record_maintain.employee'),
            preserve_default=False,
        ),
    ]
